# Generated by Django 6.0.7 on 2026-07-16 07:38

from django.db import migrations, models


def backfill_blank_phone_numbers(apps, schema_editor):
    # Blank phone_number becomes NULL below, but multiple existing '' values
    # would collide under the new unique constraint before that conversion
    # runs — give each a distinct placeholder first so the alter succeeds.
    User = apps.get_model('common', 'User')
    for user in User.objects.filter(phone_number=''):
        user.phone_number = f'PENDING-{user.pk}'
        user.save(update_fields=['phone_number'])


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill_blank_phone_numbers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
